name: Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispath:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [ Debug, Release ]
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore MicGuard.slnx

      - name: Build
        run: dotnet build MicGuard.slnx --no-restore --configuration ${{ matrix.configuration }}